# Use the official .NET 8 SDK image to build the application
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ProjectApi/ProjectApi.csproj ProjectApi/
RUN dotnet restore ProjectApi/ProjectApi.csproj
COPY . .
WORKDIR /src/ProjectApi
RUN dotnet build ProjectApi.csproj -c Release -o /app/build

FROM build AS publish
RUN dotnet publish ProjectApi.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 5001
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ProjectApi.dll"]